apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: desafio-15-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dylan010/helm-cd-argo
    targetRevision: HEAD
    path: desafio-15-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: desafio-15-helm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true